jasypt:
   encryptor:
      password: ${jasyptpwd:secretkey}
      algorithm: PBEWithMD5AndDES

server:
   port: 8180
   servlet:
      context-path: /consultorio-psicologico
      session:
         timeout: 21600s
springdoc:
   swagger-ui:
      path: /swagger-ui.html
spring:
   datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
      jdbcUrl: jdbc:mysql://localhost:3306/consultoriopsi?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
      username: root
      password: Ceibapsi0826*
      hikari:
         poolName: pool
